<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI1Yc49x\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI1Yc49x/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerI1Yc49x.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerI1Yc49x\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerI1Yc49x\App_KernelProdContainer([
    'container.build_hash' => 'I1Yc49x',
    'container.build_id' => 'c8a44360',
    'container.build_time' => 1660176834,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI1Yc49x');
