<?php

namespace ContainerE96cjSB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMyPostControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\MyPostController' shared autowired service.
     *
     * @return \App\Controller\MyPostController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\MyPostController'] = $instance = new \App\Controller\MyPostController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\MyPostController', $container));

        return $instance;
    }
}
