<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFCvMjrF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFCvMjrF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFCvMjrF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFCvMjrF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFCvMjrF\App_KernelDevDebugContainer([
    'container.build_hash' => 'FCvMjrF',
    'container.build_id' => '6a54a2ac',
    'container.build_time' => 1659986158,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFCvMjrF');
