<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXumF2cV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXumF2cV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXumF2cV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXumF2cV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXumF2cV\App_KernelDevDebugContainer([
    'container.build_hash' => 'XumF2cV',
    'container.build_id' => '5e50397b',
    'container.build_time' => 1660042843,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXumF2cV');
